### ISSUE TITLE
No license specified for GUID-Partition-Table-Parser

### ISSUE THREAD

**Issue by aperezbios** [KirollousMoheb/GUID-Partition-Table-Parser#1]
@KirollousMoheb there's no license specified for the contents of this file/repository. Is this your original work? If so, would you be willing to assign a license to it? I can't use it as-is, but would like to, as it's the most minimal implementation I've found so far. Thank you!

**Comment by KirollousMoheb** [comment]
Yes it is my original work. I added a license you can use it now. Good luck!
